site_name: My Docs
nav:
    - Introduction: index.md
    - Steps:
        - Environment: Environment.md
        - Mkdocs Project Build: Git-Build.md
        - Travis Setting: Travis-Setting.md
        - Travis Build: Travis-Build.md
        - GitHub Pages: GitHub-Pages.md
        - Math Support: Math-Support.md
        - Extensions: Extensions.md
    - About: about.md
theme:
  name: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - toc:
        baselevel: 3
        permalink: true
    - mdx_math
    - pymdownx.arithmatex
    - admonition
    - pymdownx.details
    - pymdownx.superfences 
